### ISSUE TITLE
ES LAYOUT NOT WORKING

### ISSUE THREAD

**Issue by LostName1** [arduino-libraries/Keyboard#55]
After trying for long time and trying all the ideas that came to my head I havent been able to make the layout work. The keycode are mixed even when I configure then manually.
![unknown](https://user-images.githubusercontent.com/57833319/140433113-62b506b4-5397-4481-b55e-e34bd0765eb5.png)
![unknown](https://user-images.githubusercontent.com/57833319/140433138-5cbeb99a-657a-4efd-90b5-eb0ab3805a1d.png)
g)

**Comment by facchinm** [comment]
Hi @LostName1 ,
we just merged yesterdary a patrch that finally allows multiple language maps :slightly_smiling_face: 
The API is very simple; just change `Keyboard.begin()` into `Keyboard.begin(KeyboardLayout_es_ES)` and you should be fine without strange hacks!
Let me know if it works fine or if you find any issue; I'm closing this in the meantime.

**Comment by LostName1** [comment]
I used that too but I got the same error

**Comment by edgar-bonet** [comment]
@LostName1 wrote:
> I got the same error

What error? You are not showing any error in the issue description.

If you are having issues making the library work for your needs, please follow these steps:

1. Consider how sure you are that you are experiencing a bug in the library, rather than a bug in you own code. If unsure, seek help on the [Arduino forum][forum] or on the [Arduino StackExchange][se]. Open an issue here _only_ if you are very confident that you have found an issue in the library itself.
2. Post one (an preferably only one) small program illustrating your problem. Post it as text, not as a screen shot.
3. Clearly describe your problem: explain what you are trying to achieve, what behavior you expect from your program, and what behavior you see instead.

Also note that the KeyboardStateView tool you use is not something everybody knows about and is poorly documented. It is unclear whether the “key codes” it displays are USB usage codes, legacy scan codes as used in old serial keyboards, or OS-specific codes. Note that codes used by this library are neither of those.

[forum]: https://forum.arduino.cc/
[se]: https://arduino.stackexchange.com/
